feat: auto-select best matching language

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -1,16 +1,41 @@
 #!/bin/sh
-
-INPUT_FILE="$1"
-OUTPUT_FILE="$2"
-
-# set ownership of output file, no matter if conversion was successful
 set -e
-finish() {
-  if [ "${PUID}" -a "${PGID}" -a -f "${OUTPUT_FILE}" ]; then
-    chown "${PUID}:${PGID}" "${OUTPUT_FILE}"
-  fi
+
+log() {
+  >&2 echo "${@}"
 }
-trap 'finish' EXIT
+
+cancel() {
+  log "Error: ${@}"
+  return 1
+}
+
+find_language() {
+  allowed_languages="${1}"
+  input_file="${2}"
+  [ "${input_file}" ] || cancel "Missing input file."
+
+  ffprobe_output=$(ffprobe -loglevel level+error -show_entries stream=index:stream_tags=language -select_streams a -of compact=p=0:nk=1 "${input_file}") \
+    || { return_code="$?"; log "${ffprobe_output}"; return "${return_code}"; }
+  available_languages=$(printf "${ffprobe_output}" | cut -d '|' -f 2 | xargs | tr ' ' ',')
+
+  for allowed_language in $(echo "${allowed_languages}" | tr ',' '\n'); do
+    for available_language in $(echo "${available_languages}" | tr ',' '\n'); do
+      if [ "${available_language}" = "${allowed_language}" ]; then
+        echo "${available_language}"
+        return 0
+      fi
+    done
+  done
+
+  [ "${allowed_languages}" ] && log "None of the requested languages [${allowed_languages}] are available."
+  cancel "Please provide at least one of the available languages: [${available_languages}]"
+}
+
+
+input_file="${1}"
+output_file="${2}"
+language=$(find_language "${AUDIO_LANGUAGES}" "${input_file}")
 
 #
 # first ffmpeg call: retain only
@@ -40,8 +65,8 @@ trap 'finish' EXIT
 #
 nice ffmpeg -hide_banner \
             -nostats \
-            -i "${INPUT_FILE}" \
-            -map 0:v -map "0:m:language:${AUDIO_LANGUAGE}" \
+            -i "${input_file}" \
+            -map 0:v -map "0:m:language:${language}" \
             -c copy \
             -f matroska - \
     | nice ffmpeg \
@@ -53,11 +78,11 @@ nice ffmpeg -hide_banner \
             -filter_hw_device foo \
             -i - \
             -map 0:v:0 -map 0:a:0 \
-            -map_metadata:s:a -1 -metadata:s:a "language=${AUDIO_LANGUAGE}" \
+            -map_metadata:s:a -1 -metadata:s:a "language=${language}" \
             -vf  "format=nv12|vaapi,hwupload,scale_vaapi=w=${VIDEO_WIDTH}:h=-1" \
             -c:v "$VIDEO_CODEC" \
             -b:v "$VIDEO_BITRATE" \
             -c:a "$AUDIO_CODEC" \
             -b:a "$AUDIO_BITRATE" \
             -ac  "$AUDIO_CHANNELS" \
-            "${OUTPUT_FILE}"
+            "${output_file}"
diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,30 +1,40 @@
 #!/bin/sh
 
-[ -z "$2" -o ! -f "$1" ] && echo "Syntax: $(basename $0) <input-file> <output-file>" && return 1
+if [ ! -f "$1" ]; then
+  >&2 echo "Missing input file: '$1'"
+  >&2 echo "Syntax: $(basename $0) <input-file> <output-file>"
+  return 1
+fi
+if [ -z "$2" ]; then
+  >&2 echo "Missing argument for output file"
+  >&2 echo "Syntax: $(basename $0) <input-file> <output-file>"
+  return 1
+fi
 
 in_fullpath=$(realpath "$1")
 in_dir_host=$(dirname  "$in_fullpath")
 in_file=$(    basename "$in_fullpath")
-out_fullpath=$(realpath "$2")
+out_fullpath=$(realpath -m "$2")
 out_dir_host=$(dirname  "$out_fullpath")
 out_file=$(    basename "$out_fullpath")
 in_dir_container='/video/in'
 out_dir_container='/video/out'
+user="${PUID:-$(id -u)}:${PGID:-$(id -g)}"
+
 env_args=''
-env_args="${env_args} -e PUID=${PUID:-$(id -u)}"
-env_args="${env_args} -e PGID=${PGID:-$(id -g)}"
-[ "${VIDEO_CODEC}"    ] && env_args="${env_args} -e VIDEO_CODEC=${VIDEO_CODEC}"
-[ "${VIDEO_BITRATE}"  ] && env_args="${env_args} -e VIDEO_BITRATE=${VIDEO_BITRATE}"
-[ "${VIDEO_WIDTH}"    ] && env_args="${env_args} -e VIDEO_WIDTH=${VIDEO_WIDTH}"
-[ "${AUDIO_CODEC}"    ] && env_args="${env_args} -e AUDIO_CODEC=${AUDIO_CODEC}"
-[ "${AUDIO_BITRATE}"  ] && env_args="${env_args} -e AUDIO_BITRATE=${AUDIO_BITRATE}"
-[ "${AUDIO_CHANNELS}" ] && env_args="${env_args} -e AUDIO_CHANNELS=${AUDIO_CHANNELS}"
-[ "${AUDIO_LANGUAGE}" ] && env_args="${env_args} -e AUDIO_LANGUAGE=${AUDIO_LANGUAGE}"
-[ "${VAAPI_DEVICE}"   ] && env_args="${env_args} -e VAAPI_DEVICE=${VAAPI_DEVICE}"
+[ "${VIDEO_CODEC}"     ] && env_args="${env_args} -e VIDEO_CODEC=${VIDEO_CODEC}"
+[ "${VIDEO_BITRATE}"   ] && env_args="${env_args} -e VIDEO_BITRATE=${VIDEO_BITRATE}"
+[ "${VIDEO_WIDTH}"     ] && env_args="${env_args} -e VIDEO_WIDTH=${VIDEO_WIDTH}"
+[ "${AUDIO_CODEC}"     ] && env_args="${env_args} -e AUDIO_CODEC=${AUDIO_CODEC}"
+[ "${AUDIO_BITRATE}"   ] && env_args="${env_args} -e AUDIO_BITRATE=${AUDIO_BITRATE}"
+[ "${AUDIO_CHANNELS}"  ] && env_args="${env_args} -e AUDIO_CHANNELS=${AUDIO_CHANNELS}"
+[ "${AUDIO_LANGUAGES}" ] && env_args="${env_args} -e AUDIO_LANGUAGES=${AUDIO_LANGUAGES}"
+[ "${VAAPI_DEVICE}"    ] && env_args="${env_args} -e VAAPI_DEVICE=${VAAPI_DEVICE}"
 
 docker-compose                               \
-  -f $(dirname "$0")/docker-compose.yml      \
+  --file $(dirname "$0")/docker-compose.yml  \
   run                                        \
+  --user "${user}"                           \
   --rm                                       \
   -v "${in_dir_host}:${in_dir_container}:ro" \
   -v "${out_dir_host}:${out_dir_container}"  \
